### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by winlianclub** [Ardianpurnama/RIDEN-RFU-#3]
I found this error with python 3

F:\WINBOT\riden
λ python riden.py
Traceback (most recent call last):
  File "riden.py", line 1, in <module>
    from GENERATOR import *
  File "F:\WINBOT\riden\GENERATOR\__init__.py", line 1, in <module>
    from .client import RIDEN
  File "F:\WINBOT\riden\GENERATOR\client.py", line 2, in <module>
    from .auth import Auth
  File "F:\WINBOT\riden\GENERATOR\auth.py", line 3, in <module>
    from .server import Server
  File "F:\WINBOT\riden\GENERATOR\server.py", line 3, in <module>
    import json, requests, urllib
  File "D:\Python36-32\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "D:\Python36-32\lib\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "D:\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 3, in <module>
    import logging
  File "D:\Python36-32\lib\logging\__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections
  File "D:\Python36-32\lib\traceback.py", line 5, in <module>
    import linecache
  File "D:\Python36-32\lib\linecache.py", line 11, in <module>
    import tokenize
  File "D:\Python36-32\lib\tokenize.py", line 35, in <module>
    from token import *
  File "F:\WINBOT\riden\token.py", line 7, in <module>
    from humanfriendly import format_timespan, format_size, format_number, format_length
  File "D:\Python36-32\lib\site-packages\humanfriendly\__init__.py", line 13, in <module>
    import multiprocessing
  File "D:\Python36-32\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "D:\Python36-32\lib\multiprocessing\context.py", line 3, in <module>
    import threading
  File "D:\Python36-32\lib\threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
ImportError: cannot import name 'format_exc'

What must i do for fix this an error ???

Regards,

Winlian Club

**Comment by Ardianpurnama** [comment]
cek my update

**Comment by adhiesatrio** [comment]
gmana bang itu error login,,,,,,

**Comment by Ardianpurnama** [comment]
Wait for update
